#
# Copyright (c) 2019, 2020 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0
#
apiVersion: v1
# Version of the Helm chart, by default, this will be the Maven project version
version: 2.0.0
# Version of the application being deployed by the chart
appVersion: 1.0.2
name: hono
description: Scalable IoT messaging platform
keywords:
  - IoT
  - messaging
home: https://www.eclipse.org/hono/
sources:
  - https://github.com/eclipse/hono
  - https://github.com/eclipse/packages
icon: https://raw.githubusercontent.com/eclipse/hono/master/logo/SVG-1-1/HONO-Logo_Bild_s-135x125px.svg
maintainers:
  - name: dejanb
    email: dbosanac@redhat.com
  - name: ctron
    email: jreimann@redhat.com
