#
# Copyright (c) 2019 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0
#
jaegerBackendExample:
  enabled: true

  service:
    annotations: {}
    loadBalancerIP:
    nodePort:

    # serviceType defines the type which the created service will have.
    # The default is "ClusterIP". 
    # Note: This property will be ignored when deploying to platform "openshift".
    type: LoadBalancer