{{- if .Values.deviceRegistryExample.enabled }}
#
# Copyright (c) 2019 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0
#
apiVersion: v1
kind: Service
metadata:
  {{- $args := dict "dot" . "component" "service-device-registry" "name" "service-device-registry-ext" }}
  {{- include "hono.metadata" $args | nindent 2 }}
  {{- with .Values.deviceRegistryExample.svc.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
  - name: http
    port: 28080
    protocol: TCP
    targetPort: http
    {{- include "hono.service.nodePort" (dict "dot" . "service" .Values.deviceRegistryExample.svc "port" "http" ) | nindent 4 }}
  - name: https
    port: 28443
    protocol: TCP
    targetPort: https
    {{- include "hono.service.nodePort" (dict "dot" . "service" .Values.deviceRegistryExample.svc "port" "https" ) | nindent 4 }}
  selector:
    {{- include "hono.matchLabels" $args | nindent 4 }}
{{- include "hono.service.type" (dict "dot" . "service" .Values.deviceRegistryExample.svc ) | nindent 2 }}
{{- include "hono.service.loadBalancerIP" (dict "dot" . "service" .Values.deviceRegistryExample.svc ) | nindent 2 }}
{{- end }}
