{{- if .Values.adapters.kura.enabled }}
#
# Copyright (c) 2019 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0
#
apiVersion: v1
kind: Service
metadata:
  {{- $args := dict "dot" . "component" "adapter-kura" "name" "adapter-kura" }}
  {{- include "hono.metadata" $args | nindent 2 }}
  {{- with .Values.adapters.kura.svc.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
  - name: mqtt
    port: 1883
    protocol: TCP
    targetPort: mqtt
    {{- include "hono.service.nodePort" (dict "dot" . "service" .Values.adapters.kura.svc "port" "mqtt" ) | nindent 4 }}
  - name: secure-mqtt
    port: 8883
    protocol: TCP
    targetPort: secure-mqtt
    {{- include "hono.service.nodePort" (dict "dot" . "service" .Values.adapters.kura.svc "port" "mqtts" ) | nindent 4 }}
  selector:
    {{- include "hono.matchLabels" $args | nindent 4 }}
{{- include "hono.service.type" (dict "dot" . "service" .Values.adapters.kura.svc ) | nindent 2 }}
{{- include "hono.service.loadBalancerIP" (dict "dot" . "service" .Values.adapters.kura.svc ) | nindent 2 }}
{{- end }}
